In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('./Mushrooms.csv')

In [6]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
0            c         n          k   ...                          s   
1            c         b          k   ...                          s   
2            c         b          n   ...                          s   
3            c         n          n   ...                          s   
4            w         b          k   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
class                       8124 non-null object
cap-shape                   8124 non-null object
cap-surface                 8124 non-null object
cap-color                   8124 non-null object
bruises                     8124 non-null object
odor                        8124 non-null object
gill-attachment             8124 non-null object
gill-spacing                8124 non-null object
gill-size                   8124 non-null object
gill-color                  8124 non-null object
stalk-shape                 8124 non-null object
stalk-root                  8124 non-null object
stalk-surface-above-ring    8124 non-null object
stalk-surface-below-ring    8124 non-null object
stalk-color-above-ring      8124 non-null object
stalk-color-below-ring      8124 non-null object
veil-type                   8124 non-null object
veil-color                  8124 non-null object
ring-number

In [8]:
df.shape   # 3672 Rows and 87 Columns

(8124, 23)

In [9]:
df.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color   ...   stalk-surface-below-ring  \
count          8124      8124       8124   ...                       8124   
unique            2         2         12   ...                          4   
top               c         b          b   ...                          s   
freq           6812      5612       1728   ...                       4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [12]:
columns = list(df.columns)

In [13]:
columns

['class',
 'cap-shape',
 'cap-surface',
 'cap-color',
 'bruises',
 'odor',
 'gill-attachment',
 'gill-spacing',
 'gill-size',
 'gill-color',
 'stalk-shape',
 'stalk-root',
 'stalk-surface-above-ring',
 'stalk-surface-below-ring',
 'stalk-color-above-ring',
 'stalk-color-below-ring',
 'veil-type',
 'veil-color',
 'ring-number',
 'ring-type',
 'spore-print-color',
 'population',
 'habitat']

In [16]:
for i in columns:
    print(i.ljust(25) + str(len(df[i].unique())))
# This will get count of all unique values    

class                    2
cap-shape                6
cap-surface              4
cap-color                10
bruises                  2
odor                     9
gill-attachment          2
gill-spacing             2
gill-size                2
gill-color               12
stalk-shape              2
stalk-root               5
stalk-surface-above-ring 4
stalk-surface-below-ring 4
stalk-color-above-ring   9
stalk-color-below-ring   9
veil-type                1
veil-color               4
ring-number              3
ring-type                5
spore-print-color        9
population               6
habitat                  7


In [17]:
 # To check null on every Columns 
df.isnull().sum()/df.shape[0]*100  

class                       0.0
cap-shape                   0.0
cap-surface                 0.0
cap-color                   0.0
bruises                     0.0
odor                        0.0
gill-attachment             0.0
gill-spacing                0.0
gill-size                   0.0
gill-color                  0.0
stalk-shape                 0.0
stalk-root                  0.0
stalk-surface-above-ring    0.0
stalk-surface-below-ring    0.0
stalk-color-above-ring      0.0
stalk-color-below-ring      0.0
veil-type                   0.0
veil-color                  0.0
ring-number                 0.0
ring-type                   0.0
spore-print-color           0.0
population                  0.0
habitat                     0.0
dtype: float64

In [18]:
# We are going to drop our Response Variable class From our Predictive Model.
X = df.drop('class',axis=1)
X.head()

cap-shape cap-surface cap-color bruises odor gill-attachment gill-spacing  \
0         x           s         n       t    p               f            c   
1         x           s         y       t    a               f            c   
2         b           s         w       t    l               f            c   
3         x           y         w       t    p               f            c   
4         x           s         g       f    n               f            w   

  gill-size gill-color stalk-shape   ...   stalk-surface-below-ring  \
0         n          k           e   ...                          s   
1         b          k           e   ...                          s   
2         b          n           e   ...                          s   
3         n          n           e   ...                          s   
4         b          k           t   ...                          s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 22 columns]

In [19]:
Y = df['class']
Y.head()

0    p
1    e
2    e
3    p
4    e
Name: class, dtype: object

In [20]:
# Let count the Count of Values.
Y.value_counts()

e    4208
p    3916
Name: class, dtype: int64

In [23]:
df.shape

(8124, 23)

In [29]:
from sklearn.preprocessing import LabelEncoder

In [33]:
le = LabelEncoder()
df['class'] = le.fit_transform(df['class'].astype(str))

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
class                       8124 non-null int64
cap-shape                   8124 non-null object
cap-surface                 8124 non-null object
cap-color                   8124 non-null object
bruises                     8124 non-null object
odor                        8124 non-null object
gill-attachment             8124 non-null object
gill-spacing                8124 non-null object
gill-size                   8124 non-null object
gill-color                  8124 non-null object
stalk-shape                 8124 non-null object
stalk-root                  8124 non-null object
stalk-surface-above-ring    8124 non-null object
stalk-surface-below-ring    8124 non-null object
stalk-color-above-ring      8124 non-null object
stalk-color-below-ring      8124 non-null object
veil-type                   8124 non-null object
veil-color                  8124 non-null object
ring-number 

In [38]:
df['class'] = df['class'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
class                       8124 non-null object
cap-shape                   8124 non-null object
cap-surface                 8124 non-null object
cap-color                   8124 non-null object
bruises                     8124 non-null object
odor                        8124 non-null object
gill-attachment             8124 non-null object
gill-spacing                8124 non-null object
gill-size                   8124 non-null object
gill-color                  8124 non-null object
stalk-shape                 8124 non-null object
stalk-root                  8124 non-null object
stalk-surface-above-ring    8124 non-null object
stalk-surface-below-ring    8124 non-null object
stalk-color-above-ring      8124 non-null object
stalk-color-below-ring      8124 non-null object
veil-type                   8124 non-null object
veil-color                  8124 non-null object
ring-number

In [39]:
Y = df['class']
Y.head()

0    1
1    0
2    0
3    1
4    0
Name: class, dtype: object

In [43]:
# To make X as Categorical Data get_Dummies() method is applied.One Hot Enconding is applied to it.
X = pd.get_dummies(X)
X.head()

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            1            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   

   cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0            1              0              0              1              0   
1            1              0              0              1              0   
2            0              0              0              1              0   
3            1              0              0              0              1   
4            1              0              0              1              0   

     ...      population_s  population_v  population_y  habitat_d  habitat_g  \
0    ...                 1             0             0          0          0   
1    ...                 0             0             0          0          1   
2    ...                 0             0             0          0          0   
3    ...                 1             0             0          0          0   
4    ...                 0             0             0          0          1   

   habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0          0          0          0          1          0  
1          0          0          0          0          0  
2          0          1          0          0          0  
3          0          0          0          1          0  
4          0          0          0          0          0  

[5 rows x 117 columns]

In [46]:
from sklearn.model_selection import train_test_split

In [47]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)

In [49]:
from sklearn.decomposition import PCA

In [50]:
pca = PCA(whiten=True)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=None, random_state=None,
  svd_solver='auto', tol=0.0, whiten=True)

In [56]:
variance = pd.DataFrame(pca.explained_variance_ratio_)

In [58]:
np.cumsum(pca.explained_variance_ratio_)
#This will tell How many Components pca need to learn to reach 1 or 100 % Learning so It learned all feature on 15.

array([0.16893779, 0.31160685, 0.4072278 , 0.4688614 , 0.50879329,
       0.54566329, 0.57709209, 0.6046741 , 0.63144205, 0.65230335,
       0.67271318, 0.69150387, 0.70958921, 0.72684478, 0.74233992,
       0.75723693, 0.7714365 , 0.78536472, 0.79853377, 0.80993992,
       0.82074538, 0.83145512, 0.84162693, 0.85101018, 0.85971901,
       0.86825704, 0.87640915, 0.8840821 , 0.89151247, 0.89862201,
       0.90514647, 0.91145333, 0.91736829, 0.92277107, 0.9281615 ,
       0.93324645, 0.93809109, 0.94272429, 0.94704314, 0.95121463,
       0.95515381, 0.95895922, 0.962487  , 0.96593304, 0.96915791,
       0.97227316, 0.97497104, 0.97733295, 0.97952636, 0.9815504 ,
       0.98337747, 0.9850328 , 0.9865183 , 0.98775488, 0.98894725,
       0.99003007, 0.99109096, 0.99200248, 0.9927965 , 0.9934584 ,
       0.9941008 , 0.99465949, 0.99520051, 0.9957319 , 0.99623579,
       0.99673029, 0.99715577, 0.99753284, 0.99786779, 0.99818213,
       0.99847824, 0.99870845, 0.9989278 , 0.99910415, 0.99927

In [60]:
#so we are reducing component ratio
pca = PCA(n_components=84,whiten=True)
pca_X_train = pca.fit_transform(X_train)
pca_X_test = pca.transform(X_test)

In [64]:
Y_test.value_counts()

0    1316
1    1122
Name: class, dtype: int64

In [61]:
#Now Scaling the Data
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [65]:
X_train = sc.fit_transform(pca_X_train)
X_test = sc.transform(pca_X_test)

In [68]:
from keras.models import Sequential
from keras.layers import Dense
model = Sequential()

In [73]:
model.add(Dense(output_dim=5 , init='uniform', activation='relu' ,input_dim=84))
model.add(Dense(output_dim=5 , init='uniform', activation='relu'))
model.add(Dense(output_dim=1 , init='uniform', activation='sigmoid'))

F:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=84, units=5, kernel_initializer="uniform")`
  """Entry point for launching an IPython kernel.
F:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=5, kernel_initializer="uniform")`
  
F:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [78]:
model.compile(optimizer='adam' , loss='binary_crossentropy',metrics=['accuracy'])
model.fit(X_train,Y_train ,batch_size=10,epochs=3 , verbose=True)

Epoch 1/3
5686/5686 [==============================] - 2s 370us/step - loss: 5.5488e-06 - acc: 1.0000
Epoch 2/3
5686/5686 [==============================] - 1s 242us/step - loss: 2.5218e-07 - acc: 1.0000
Epoch 3/3
5686/5686 [==============================] - 1s 247us/step - loss: 1.2871e-07 - acc: 1.0000


In [87]:
y_pred = model.predict(X_test)

In [88]:
y_pred

array([[9.9999988e-01],
       [1.0000000e+00],
       [4.6251689e-08],
       ...,
       [4.2851436e-08],
       [9.9999988e-01],
       [5.7186242e-08]], dtype=float32)

In [89]:
y_pred = (y_predict > 0.5)
y_pred

array([[ True],
       [ True],
       [False],
       ...,
       [False],
       [ True],
       [False]])

In [96]:
Y_test = Y_test.astype(int)

In [100]:
# lets check Test data and Predicted Value of Test Data
from sklearn.metrics import accuracy_score 
accuracy_score(Y_test,y_pred)

1.0

In [98]:
# Confusion Matrix is used to find Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,y_pred)

In [99]:
cm

array([[1316,    0],
       [   0, 1122]], dtype=int64)